name: test-machines
version: 0.0.0.0

ghc-options: -Wall

default-extensions:
  - OverloadedStrings
  - TypeFamilies

dependencies:
  - base
  - meals
  - optparse-applicative
  - random
  - text

library:
  source-dirs: src

executables:
  even-process:
    main: Main.hs
    source-dirs: machines/even
    dependencies:
      - test-machines

tests:
  doctest:
    main: DocTest.hs
    source-dirs: test
    dependencies:
      - test-machines
      - doctest

  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - test-machines
      - hspec
